package com.example.videodownloader.core.text

import android.content.Context
import com.example.videodownloader.R

class AndroidAppText(
    private val context: Context,
) : AppText {
    override fun inputRequired() = context.getString(R.string.text_input_required)
    override fun invalidLink() = context.getString(R.string.text_invalid_link)
    override fun nonDownloadableOption() = context.getString(R.string.text_non_downloadable_option)
    override fun downloadQueued() = context.getString(R.string.text_download_queued)
    override fun taskNotFound() = context.getString(R.string.text_task_not_found)
    override fun missingSystemDownloadId() = context.getString(R.string.text_missing_system_download_id)
    override fun downloadSuccess() = context.getString(R.string.text_download_success)
    override fun downloadFailed() = context.getString(R.string.text_download_failed)
    override fun downloadCanceled() = context.getString(R.string.text_download_canceled)
    override fun taskQueued() = context.getString(R.string.text_task_queued)
    override fun downloading() = context.getString(R.string.text_downloading)
    override fun downloadedFileMissing() = context.getString(R.string.text_downloaded_file_missing)
    override fun downloadedFileEmpty() = context.getString(R.string.text_downloaded_file_empty)
    override fun downloadedPlaylistNotMerged() = context.getString(R.string.text_downloaded_playlist_not_merged)
    override fun downloadedHtmlInsteadOfVideo() = context.getString(R.string.text_downloaded_html_instead_of_video)
    override fun downloadedImageInvalid() = context.getString(R.string.text_downloaded_image_invalid)
    override fun downloadedVideoInvalid() = context.getString(R.string.text_downloaded_video_invalid)
    override fun downloadTaskMissingOrCleaned() = context.getString(R.string.text_download_task_missing_or_cleaned)
    override fun downloadStatusUnknown() = context.getString(R.string.text_download_status_unknown)
    override fun downloadCanceledByUser() = context.getString(R.string.text_download_canceled_by_user)
    override fun m3u8DownloadFailed() = context.getString(R.string.text_m3u8_download_failed)
    override fun downloadTaskMissingOrCleared() = context.getString(R.string.text_download_task_missing_or_cleared)
    override fun downloadCannotResume(reason: Int) = context.getString(R.string.text_download_cannot_resume, reason)
    override fun storageDeviceNotFound() = context.getString(R.string.text_storage_device_not_found)
    override fun targetFileAlreadyExists() = context.getString(R.string.text_target_file_already_exists)
    override fun fileReadWriteFailed(reason: Int) = context.getString(R.string.text_file_read_write_failed, reason)
    override fun networkDataError(reason: Int) = context.getString(R.string.text_network_data_error, reason)
    override fun insufficientStorage() = context.getString(R.string.text_insufficient_storage)
    override fun tooManyRedirects() = context.getString(R.string.text_too_many_redirects)
    override fun serverStatusError(reason: Int) = context.getString(R.string.text_server_status_error, reason)
    override fun unknownDownloadError(reason: Int) = context.getString(R.string.text_unknown_download_error, reason)
    override fun genericDownloadFailed(reason: Int) = context.getString(R.string.text_generic_download_failed, reason)
    override fun downloadPreflightHttpFailed(code: Int) = context.getString(R.string.text_download_preflight_http_failed, code)
    override fun downloadNonVideoContentType(contentType: String) = context.getString(R.string.text_download_non_video_content_type, contentType)
    override fun downloadOptionNotPlayable() = context.getString(R.string.text_download_option_not_playable)
    override fun parseNoDisplayableMedia() = context.getString(R.string.text_parse_no_displayable_media)
    override fun xNetworkUnavailable() = context.getString(R.string.text_x_network_unavailable)
    override fun parseNoDownloadableVideo() = context.getString(R.string.text_parse_no_downloadable_video)
    override fun parserInitFailed() = context.getString(R.string.text_parser_init_failed)
    override fun xAuthFailedWithCookie() = context.getString(R.string.text_x_auth_failed_with_cookie)
    override fun xAuthFailedWithoutCookie() = context.getString(R.string.text_x_auth_failed_without_cookie)
    override fun xNoVideoWithNetworkIssue() = context.getString(R.string.text_x_no_video_with_network_issue)
    override fun xNoVideoFound() = context.getString(R.string.text_x_no_video_found)
    override fun xAccessFailed() = context.getString(R.string.text_x_access_failed)
    override fun xTemporaryParseFailed() = context.getString(R.string.text_x_temporary_parse_failed)
    override fun xCookieRequired() = context.getString(R.string.text_x_cookie_required)
    override fun xCookieMissingFields() = context.getString(R.string.text_x_cookie_missing_fields)
    override fun xCookieExpired() = context.getString(R.string.text_x_cookie_expired)
    override fun xCookieValidationSkipped() = context.getString(R.string.text_x_cookie_validation_skipped)
    override fun originalQuality() = context.getString(R.string.text_original_quality)
    override fun segmentedStream() = context.getString(R.string.text_segmented_stream)
    override fun directVideoTitle() = context.getString(R.string.text_direct_video_title)
    override fun douyinImageParseFailed() = context.getString(R.string.text_douyin_image_parse_failed)
    override fun douyinVideoTitle() = context.getString(R.string.text_douyin_video_title)
    override fun douyinGalleryTitle() = context.getString(R.string.text_douyin_gallery_title)
    override fun gifLabel(index: Int) = context.getString(R.string.text_gif_label, index)
    override fun imageLabel(index: Int) = context.getString(R.string.text_image_label, index)
    override fun xBroadcastTitle() = context.getString(R.string.text_x_broadcast_title)
    override fun xVideoTitle() = context.getString(R.string.text_x_video_title)
    override fun webVideoTitle() = context.getString(R.string.text_web_video_title)
}
